name: secure_clipboard_ios
version: 0.1.1
description: iOS implementation of the secure_clipboard Flutter plugin.
homepage: https://github.com/Amansrivastava534/secure_clipboard
repository: https://github.com/Amansrivastava534/secure_clipboard

environment:
  sdk: ">=3.0.0 <4.0.0"
  flutter: ">=3.0.0"

flutter:
  plugin:
    implements: secure_clipboard
    platforms:
      ios:
        pluginClass: SecureClipboardIosPlugin

dependencies:
  flutter:
    sdk: flutter
  secure_clipboard_platform_interface: ^0.1.1
  plugin_platform_interface: ^2.1.8
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
